Lecci√≥n 8: Gesti√≥n y manejo de errores y excepciones
Categor√≠a: Flask
flask, medio, python, tutorial flask
Lecci√≥n 8 Gesti√≥n de errores
Errores. Toda aplicaci√≥n es susceptible a errores. Incluso aunque nuestro c√≥digo sea perfecto, siempre puede haber alg√∫n bug en una librer√≠a de un tercero u ocurrir un fallo en la base de datos, en la red, en un servicio externo‚Ä¶ Por eso es importante esta parte del tutorial.

En esta lecci√≥n vamos a repasar una serie de conceptos b√°sicos sobre manejo de errores y las herramientas que nos proporciona Flask para ello. Y es que es important√≠simo de cara a nuestros usuarios que la aplicaci√≥n sea lo m√°s robusta posible, es decir, que al usuario se le presenten el m√≠nimo n√∫mero de errores. Da muy mala imagen que a un usuario se le muestre, por ejemplo, una traza de error o un mensaje como Error 500: Internal Server Error. Todo este tipo de cosas no deber√≠an llegar a nuestros usuarios.

¬øEst√°s list@ para saber c√≥mo manejar los errores? ¬°Comencemos! Pero antes, ¬°recuerda! Este tutorial es la continuaci√≥n de la Lecci√≥n 7. As√≠ que si te has despistado o no has seguido todas las lecciones del tutorial, puedes descargar el c√≥digo por donde lo dejamos como te indico a continuaci√≥n:

‚ÄºÔ∏è ATENCI√ìN ‚ÄºÔ∏è

üéØ Puedes descargar el c√≥digo correspondiente a la Lecci√≥n 7 desde el siguiente repositorio de Github:

git clone https://github.com/j2logo/tutorial-flask.git
git checkout tags/leccion7 -b leccion7

√çndice
Aqu√≠ tienes los puntos principales de esta lecci√≥n:

Introducci√≥n
Qu√© sucede cu√°ndo hay un error no controlado
abort
Manejadores de errores
Introducci√≥n
Como te dec√≠a al comienzo de este post, cualquier aplicaci√≥n puede fallar en el momento m√°s inesperado. Por mucho que nos esforcemos en programar teniendo en cuenta hasta el m√°s m√≠nimo detalle, los errores siempre pueden suceder. Entre los errores m√°s t√≠picos encontramos:

Errores de programaci√≥n. S√≠, el error m√°s t√≠pico es que el c√≥digo tenga un bug.
Errores al escribir en un fichero: el fichero ya existe, no hay permisos de escritura en un directorio, ‚Ä¶
Errores de base de datos: de integridad, permisos, fallos de conexi√≥n, ‚Ä¶
Errores al conectar con un servicio externo: permisos de acceso, indisponibilidad, errores de conexi√≥n, ‚Ä¶
Como vemos, nunca sabemos cu√°ndo, d√≥nde ni c√≥mo nuestra aplicaci√≥n va a fallar. Por eso, lo mejor que podemos hacer es ponerle remedio en la medida de lo posible con las herramientas que nos facilita cada lenguaje de programaci√≥n y cada framework. En nuestro caso, Python y Flask, respectivamente.

Qu√© sucede cuando hay un error no controlado
En el caso de una aplicaci√≥n web, lo m√°s com√∫n cuando ocurre un error no controlado es que al usuario se le muestre una p√°gina de error, acompa√±ada de un c√≥digo de estado HTTP. Estas p√°ginas de error bien las sirve la propia aplicaci√≥n, bien el servidor web en funci√≥n del c√≥digo de estado devuelto por la respuesta de la aplicaci√≥n.

Los c√≥digos de estado HTTP sirven para clasificar los posibles errores sucedidos durante el procesamiento de la petici√≥n HTTP. Entre los m√°s comunes se encuentran:

200: La petici√≥n se proces√≥ correctamente.
4xx: Hubo un problema relacionado con la petici√≥n. Normalmente relacionados con el cliente o el usuario.
5xx: Hubo un problema en la parte del servidor. Suelen ser fallos en la aplicaci√≥n.
No es el prop√≥sito de este post hablar sobre los c√≥digos de estado. Si quieres saber m√°s puedes aprender sobre ello aqu√≠.

Ejemplos de errores no controlados
Siguiendo con nuestro c√≥digo del tutorial, imaginemos que tratamos de acceder a la p√°gina http://localhost:5000/contacto

Efectivamente, al acceder nos aparecer√° un error indicando que la p√°gina no existe como el que muestro a continuaci√≥n:

Errores: p√°gina no encontrada
Ahora vamos a a√±adir un poco de acci√≥n üòú Abre el fichero public/routes.py y a√±ade al final del todo la siguiente vista:

@public_bp.route("/error")
def show_error():
    res = 1 / 0
    posts = Post.get_all()
    return render_template("public/index.html", posts=posts)
El ejemplo es muy tonto, hace lo mismo que la funci√≥n index() solo que he a√±adido un error a prop√≥sito: una divisi√≥n por cero. Como bien sabr√°s, esto produce una excepci√≥n en cualquier lenguaje de programaci√≥n. Compru√©balo t√∫ mism@. Si ahora intentas acceder a http://localhost:5000/error, se mostrar√° la siguiente p√°gina:

Errores: divisi√≥n por cero
Realmente vemos esta p√°gina porque en su d√≠a configuramos la aplicaci√≥n para arrancar con el modo DEBUG activo, dado que estamos en un entorno de desarrollo (local). El modo debug hace que veamos la traza completa del error.

Estos errores no se deber√≠an mostrar al usuario, primero porque dan mala imagen y segundo porque damos pistas sobre nuestro c√≥digo, lo que puede suponer un problema de seguridad

Si desactivamos el modo DEBUG y volvemos a acceder a la p√°gina anterior, veremos que en esta ocasi√≥n se nos muestra una p√°gina de error gen√©rica:

Error 500
Los dos ejemplos anteriores muestran los casos de un error no controlado producido por el usuario (quiere acceder a una p√°gina que no existe) y un error no controlado producido por un bug en el c√≥digo (divisi√≥n por cero). En las siguientes secciones veremos c√≥mo podemos tratar estos errores para hacer que la aplicaci√≥n sea robusta.

abort
Muchas veces, al programar, somos conscientes que el programa o la aplicaci√≥n no puede continuar su ejecuci√≥n porque hemos detectado una situaci√≥n de error. En este caso, lo que tiene m√°s sentido es interrumpir la ejecuci√≥n e informar de ello al usuario.

En el caso de Flask contamos con la funci√≥n abort(). Esta funci√≥n detiene la ejecuci√≥n de la petici√≥n de forma prematura y devuelve un c√≥digo de estado HTTP permitido (el que le pasemos como par√°metro).

Ve√°moslo con calma. Abre el fichero public/routes.py y f√≠jate en la funci√≥n show_post():

@public_bp.route("/p/<string:slug>/")
def show_post(slug):
    post = Post.get_by_slug(slug)
    if post is None:
        abort(404)
    return render_template("public/post_view.html", post=post)
En esta funci√≥n, si no encontramos ning√∫n post con el slug pasado como par√°metro, no podemos mostrar la p√°gina del post, post_view.html. Por ello, es mejor detener la ejecuci√≥n de la petici√≥n, indicando un c√≥digo de estado 404 (No encontrado). Haz la prueba. Trata de acceder a un post que no exista. Ver√°s de nuevo la p√°gina 404 Not Found üò©

Si modific√°ramos el c√≥digo de estado y en su lugar establecemos el valor 400, al acceder, la p√°gina de error ser√≠a distinta. Mostrar√≠a el error 400 Bad Request.

‚ùóÔ∏è Cuando manejes y/o gestiones las situaciones de error, utiliza la funci√≥n abort() con el c√≥digo de estado m√°s apropiado a cada caso.

Manejadores de errores
Hasta aqu√≠ hemos visto que cuando sucede un error no controlado o ejecutamos la funci√≥n abort(), al usuario se le muestra una p√°gina de error dependiente del c√≥digo de estado devuelto por la petici√≥n. Sin embargo, estas p√°ginas de error se pueden personalizar para que, por ejemplo, sigan el mismo estilo o plantilla que el resto de nuestra web. ¬øC√≥mo podemos hacer esto? A trav√©s de los manejadores de errores.

Como su nombre indica, los manejadores de errores son funciones que se ejecutan cuando se produce una situaci√≥n de error. Son muy √∫tiles porque nos permiten hacer multitud de cosas cuando ocurre un error: escribir en un log, mostrar una p√°gina de error personalizada, a√±adir una cabecera a la respuesta, etc.

Hay dos formas de definir un manejador de error:

Decorando una funci√≥n con errorhandler()
Registrando una funci√≥n como errorhandler: app.register_error_handler(codigo_estado, funcion)
Se pueden manejar dos tipos de errores:

C√≥digos de estado HTTP conocidos
Excepciones
¬øQu√© quiere decir lo anterior? Hasta ahora hab√≠amos visto que para detener la ejecuci√≥n de una petici√≥n e informar de un error hac√≠amos uso de la funci√≥n abort(). No obstante, tambi√©n es posible lanzar una excepci√≥n y asociarla a un manejador de error.

Mejor veamos todo esto con un ejemplo, ¬øno?

P√°ginas de error personalizadas
Abre el fichero app/__init__.py y a√±ade al final del todo el siguiente c√≥digo:

def register_error_handlers(app):
    @app.errorhandler(500)
    def base_error_handler(e):
        return render_template('500.html'), 500
    @app.errorhandler(404)
    def error_404_handler(e):
        return render_template('404.html'), 404
A√±ade tambi√©n lo siguiente al final del m√©todo create_app(), justo antes del return app:

    ...
    from .public import public_bp
    app.register_blueprint(public_bp)
    # Custom error handlers
    register_error_handlers(app)
    return app
Como ves, lo que estamos haciendo es devolver p√°ginas de error personalizadas para los errores 404 y 500.

¬°OJO! En el manejador del error, adem√°s de indicar el nombre de la p√°gina a renderizar, se devuelve como segundo par√°metro el c√≥digo de estado (500 y 404, respectivamente). Recuerda a√±adirlos siempre.

Tan solo falta crearlas. Vamos a ello üí™üèª Crea un fichero con nombre 404.html y otro llamado 500.html en el directorio app/templates/.

Abre el fichero 404.html y a√±ade el siguiente c√≥digo:

{% extends 'base_template.html' %}
{% block content %}
    Ooops!! La p√°gina que buscas no existe xD
{% endblock %}
Haz lo mismo con el fichero 500.html pero con este otro contenido:

{% extends 'base_template.html' %}
{% block content %}
    Ooops!! Parece que ha habido un error :(
{% endblock %}
Si ahora accedemos a un post que no existe, veremos nuestra p√°gina de error 404 personalizada:

P√°gina error 404 personalizada
Por √∫ltimo y antes de terminar esta secci√≥n, recuerda que te he comentado que adem√°s de tratar c√≥digos de estado HTTP tambi√©n se pueden manejar excepciones. Vamos a actualizar la funci√≥n show_post() como te muestro a continuaci√≥n:

from werkzeug.exceptions import NotFound
@public_bp.route("/p/<string:slug>/")
def show_post(slug):
    post = Post.get_by_slug(slug)
    if post is None:
        raise NotFound(slug)
    return render_template("public/post_view.html", post=post)
Como puedes ver, en esta ocasi√≥n, en lugar de llamar a la funci√≥n abort con el c√≥digo de estado 404, lanzamos la excepci√≥n NotFound que hereda de werkzeug.exceptions.HTTPException.

Al lanzarse la excepci√≥n, esta ser√° manejada por el manejador definido por @app.errorhandler(404) ya que el c√≥digo de estado y el c√≥digo de cualquier excepci√≥n que herede de HTTPException son los mismos. Es decir, 404 = NotFound.code

Pero no solo podemos definir excepciones que hereden de HTTPException en los manejadores de errores. Podemos controlar cualquier excepci√≥n que nosotros queramos.

¬°ATENCI√ìN! No es una buena pr√°ctica registrar un manejador de error para la excepci√≥n Exception. Este manejador podr√≠a devolver un c√≥digo de estado 500 para excepciones que hereden de HTTPException que no hayan sido controladas.

Conclusi√≥n
Bueno, hemos llegado al final de esta lecci√≥n. Aqu√≠ te he mostrado los conceptos b√°sicos sobre control de errores en una aplicaci√≥n con Flask:

La importancia de comprender que cualquier aplicaci√≥n es susceptible a fallos.
Hay que ocultar los errores internos de la aplicaci√≥n a los usuarios.
Los errores se deben comunicar de forma amigable (con p√°ginas de error, por ejemplo).
Uso de la funci√≥n abort() para interrumpir una petici√≥n cuando se detecta un error con un c√≥digo de estado. De forma alternativa se puede lanzar una excepci√≥n.
C√≥mo se definen manejadores de errores para tratar los casos de error de forma personalizada.
Tan solo queda que apliques todo esto en tu d√≠a a d√≠a y, ya sabes, si tienes cualquier duda, puedes consultarme dej√°ndome un mensaje al final del post, por email o a trav√©s de mis redes sociales.

‚ÄºÔ∏è ATENCI√ìN ‚ÄºÔ∏è

üéØ Puedes descargar el c√≥digo correspondiente a la Lecci√≥n 8 desde el siguiente repositorio de Github:

git clone https://github.com/j2logo/tutorial-flask.git
git checkout tags/leccion8 -b leccion8

En el siguiente tutorial veremos c√≥mo usar mensajes de log en Flask para conocer la traza de ejecuci√≥n de la aplicaci√≥n y registrar errores, de manera que podamos identificar bugs y corregirlos. Nos vemos.